accent = "#d4a54a"
cursor = "#d4a54a"
foreground = "#e8d5b7"
background = "#070324"

selection_foreground = "#1e1e2e"
selection_background = "#d4a54a"

color0  = "#070324"          # black
color1  = "#de6448"         # red
color2  = "#30dd50"       # green
color3  = "#d4a54a"        # yellow
color4  = "#4c99e5"        # blue
color5  = "#bd6ee1"     # magenta
color6  = "#6a9a9a"        # cyan
color7  = "#e8d5b7"       # white

color8  = "#24146b"     # bright black
color9  = "#e4836c"  # bright red
color10 = "#4fe26a" # bright green
color11 = "#f0c860" # bright yellow
color12 = "#66a8e8" # bright blue
color13 = "#c683e5" # bright magenta
color14 = "#80a9a9" # bright cyan
color15 = "#e9d7ba" # bright white
