foreground = #e8d5b7
background = #070324

selection-foreground = #1e1e2e
selection-background = #d4a54a

cursor-color = #f0c860

palette = 0=#070324
palette = 8=#0f0544

palette = 1=#e07a5f
palette = 9=#e6947f

palette = 2=#8bba7a
palette = 10=#9cc48d

palette = 3=#d4a54a
palette = 11=#f0c860

palette = 4=#4a6a9a
palette = 12=#6580a9

palette = 5=#c4a0b0
palette = 13=#ccaebb

palette = 6=#6a9a9a
palette = 14=#80a9a9

palette = 7=#e8d5b7
palette = 15=#e9d7ba
