$activeBorderColor = rgb(e8d5b7)

general {
    gaps_in = 3
    gaps_out = 4
    border_size = 2
    col.active_border = rgb(d4a54a) rgb(070324) rgb(070324) rgb(d4a54a) 30deg
    col.inactive_border = rgb(201165) rgb(070324) rgb(070324) rgb(070324) 90deg
    resize_on_border = true
    extend_border_grab_area = 15
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 6
}
